import PartsList from '../../components/PartsList';
import ServicesList from '../../components/ServicesList';
import TotalsSection from './TotalsSection';

export default function JobBillingSections({
  canSendEmail,
  canWrite,
  canManageJobCharges,
  canManageShopTax,
  canRecordJobPayments,
  canIssuePaymentAdjustments,
  canFinalizeJobInvoices,
  createEstimateLink,
  changeInvoiceFinalization,
  draftJob,
  finalizationReason,
  inventoryParts,
  inventorySearch,
  isInventoryLoading,
  isCreatingPublicEstimateLink,
  isChangingInvoiceState,
  isRecordingPayment,
  onAddInventoryPart,
  onAddPart,
  onAddPayment,
  onAddService,
  onEmailInvoice,
  onEmailEstimate,
  publicEstimateLink,
  onRemovePart,
  onRemoveService,
  onSearchInventoryParts,
  onUpdateDiscountField,
  onUpdatePart,
  onUpdateService,
  onUpdateTaxField,
  onUseShopTaxRate,
  onOpenTaxSettings,
  part,
  parts,
  payment,
  paymentTargets,
  payments,
  service,
  services,
  setInventorySearch,
  setFinalizationReason,
  setPart,
  setPayment,
  setService,
  shopTaxCalculationMode,
  shopTaxRate,
  taxSettings,
  totals
}) {
  return (
    <>
      <PartsList
        canWrite={canWrite && canManageJobCharges}
        inventoryParts={inventoryParts}
        inventorySearch={inventorySearch}
        isInventoryLoading={isInventoryLoading}
        part={part}
        parts={parts}
        setInventorySearch={setInventorySearch}
        setPart={setPart}
        onAddInventoryPart={onAddInventoryPart}
        onAddPart={onAddPart}
        onRemovePart={onRemovePart}
        onSearchInventoryParts={onSearchInventoryParts}
        onUpdatePart={onUpdatePart}
      />
      <ServicesList
        canWrite={canWrite && canManageJobCharges}
        services={services}
        service={service}
        setService={setService}
        onAddService={onAddService}
        onUpdateService={onUpdateService}
        onRemoveService={onRemoveService}
      />
      <TotalsSection
        canSendEmail={canSendEmail}
        canWrite={canWrite}
        canManageJobCharges={canManageJobCharges}
        canManageShopTax={canManageShopTax}
        canRecordJobPayments={canRecordJobPayments}
        canIssuePaymentAdjustments={canIssuePaymentAdjustments}
        canFinalizeJobInvoices={canFinalizeJobInvoices}
        createEstimateLink={createEstimateLink}
        changeInvoiceFinalization={changeInvoiceFinalization}
        addPayment={onAddPayment}
        draftJob={draftJob}
        emailInvoice={onEmailInvoice}
        emailEstimate={onEmailEstimate}
        publicEstimateLink={publicEstimateLink}
        finalizationReason={finalizationReason}
        isCreatingPublicEstimateLink={isCreatingPublicEstimateLink}
        isChangingInvoiceState={isChangingInvoiceState}
        isRecordingPayment={isRecordingPayment}
        payment={payment}
        paymentTargets={paymentTargets}
        payments={payments}
        setPayment={setPayment}
        setFinalizationReason={setFinalizationReason}
        taxSettings={taxSettings}
        shopTaxCalculationMode={shopTaxCalculationMode}
        shopTaxRate={shopTaxRate}
        totals={totals}
        updateDiscountField={onUpdateDiscountField}
        updateTaxField={onUpdateTaxField}
        useShopTaxRate={onUseShopTaxRate}
        onOpenTaxSettings={onOpenTaxSettings}
      />
    </>
  );
}
