const FENDER_ELECTRIC_MODELS = [
  'Stratocaster',
  'Telecaster',
  'Jazzmaster',
  'Jaguar',
  'Mustang',
  'Duo-Sonic',
  'Lead',
  'Starcaster',
  'Meteora',
  'Jag-Stang',
  'Esquire',
  'Electric XII'
];

const FENDER_BASS_MODELS = [
  'Precision Bass',
  'Jazz Bass',
  'Mustang Bass',
  'Jaguar Bass',
  'Dimension Bass',
  'Bass VI'
];

const GIBSON_FAMILY_MODELS = [
  'Les Paul',
  'SG',
  'ES-335',
  'ES-339',
  'ES-345',
  'ES-355',
  'Flying V',
  'Explorer',
  'Firebird',
  'Thunderbird',
  'J-45',
  'Hummingbird',
  'Dove',
  'SJ-200',
  'L-00',
  'J-200',
  'Casino',
  'Sheraton',
  'Riviera',
  'Wilshire',
  'Coronet'
];

const PRS_MODELS = [
  'Custom 24',
  'Custom 22',
  'McCarty',
  'McCarty 594',
  'Silver Sky',
  'DGT',
  'CE 24',
  'SE Custom 24',
  'SE Standard',
  'SE Hollowbody',
  'S2 Custom 24',
  'S2 McCarty 594',
  'Mira',
  'Starla',
  'Santana'
];

const IBANEZ_ELECTRIC_MODELS = [
  'RG',
  'S',
  'AZ',
  'JEM',
  'JS',
  'RGA',
  'RGR',
  'RGT',
  'Talman',
  'Iceman',
  'Roadstar',
  'Artcore',
  'AR',
  'AX',
  'Q Series'
];

const IBANEZ_BASS_MODELS = [
  'SR',
  'BTB',
  'Talman Bass',
  'EHB',
  'ATK',
  'Soundgear'
];

const ESP_LTD_MODELS = [
  'EC',
  'Eclipse',
  'Horizon',
  'M Series',
  'MH',
  'SN',
  'TE',
  'Viper',
  'Arrow',
  'Phoenix',
  'Surveyor',
  'B Series',
  'F Series'
];

const MUSIC_MAN_MODELS = [
  'StingRay',
  'StingRay Bass',
  'Cutlass',
  'Sabre',
  'Axis',
  'Luke',
  'Majesty',
  'JP',
  'Albert Lee',
  'Valentine',
  'Mariposa',
  'Bongo',
  'Sterling Bass'
];

export const INSTRUMENT_CATALOG = {
  Electric: {
    label: 'Electric Guitar',
    aliases: ['Electric Guitar'],
    brands: {
      Fender: FENDER_ELECTRIC_MODELS,
      Squier: FENDER_ELECTRIC_MODELS,
      Gibson: GIBSON_FAMILY_MODELS,
      Epiphone: GIBSON_FAMILY_MODELS,
      PRS: PRS_MODELS,
      Ibanez: IBANEZ_ELECTRIC_MODELS,
      ESP: ESP_LTD_MODELS,
      LTD: ESP_LTD_MODELS,
      Schecter: ['C-1', 'Omen', 'Demon', 'Hellraiser', 'Reaper', 'Sun Valley Super Shredder', 'Solo-II', 'PT', 'Nick Johnston', 'Stiletto'],
      Jackson: ['Dinky', 'Soloist', 'Rhoads', 'Kelly', 'King V', 'Warrior', 'Monarkh', 'Concert Bass'],
      Charvel: ['San Dimas', 'So-Cal', 'DK24', 'Pro-Mod', 'Surfcaster'],
      Gretsch: ['Streamliner', 'Electromatic', 'White Falcon', 'Country Gentleman', 'Duo Jet', 'Jet', 'Tennessee Rose', 'G5420', 'G6120', 'G6136', 'G5230'],
      Yamaha: ['Pacifica', 'Revstar', 'SA', 'SG'],
      'G&L': ['ASAT', 'Legacy', 'Comanche', 'S-500', 'Fallout', 'Doheny'],
      'Music Man': MUSIC_MAN_MODELS,
      'Sterling by Music Man': MUSIC_MAN_MODELS,
      'Ernie Ball Music Man': MUSIC_MAN_MODELS,
      Rickenbacker: ['330', '360', '325', '620', '660'],
      Danelectro: ['59', 'DC', 'U2', 'Longhorn', 'Baritone'],
      Duesenberg: ['Starplayer', 'Caribou', 'Paloma', 'Senior', 'Fullerton'],
      Suhr: ['Classic S', 'Classic T', 'Modern', 'Alt T', 'Standard'],
      'Tom Anderson': ['Drop Top', 'Classic', 'T Classic', 'Angel', 'Raven'],
      Kiesel: ['Aries', 'Theos', 'Delos', 'Solo', 'Vader', 'Zeus'],
      Carvin: ['DC', 'CT', 'Bolt', 'SH', 'V220'],
      Reverend: ['Double Agent', 'Sensei', 'Jetstream', 'Charger', 'Club King', 'Warhawk'],
      Godin: ['Summit', 'Session', 'Stadium', 'LG', 'Montreal', 'Multiac'],
      Eastman: ['T59', 'T64', 'T486', 'SB59', 'Romeo', 'Juliet'],
      Guild: ['Starfire', 'S-100', 'Surfliner', 'Polara', 'Jetstar'],
      Harmony: ['Silhouette', 'Juno', 'Rebel', 'Comet', 'Bobkat'],
      Hagstrom: ['Viking', 'Swede', 'Super Swede', 'Fantomen', 'Impala'],
      EVH: ['Wolfgang', '5150', 'Stripe Series'],
      Dean: ['ML', 'Z', 'V', 'Cadillac', 'Icon'],
      'BC Rich': ['Mockingbird', 'Warlock', 'Bich', 'Eagle', 'Ironbird'],
      Kramer: ['Baretta', 'Pacer', 'SM-1', 'Striker', 'Jersey Star'],
      Washburn: ['N Series', 'Parallaxe', 'Idol', 'WI', 'HB'],
      Cort: ['G Series', 'X Series', 'KX', 'Manson', 'CR'],
      'Harley Benton': ['Fusion', 'SC', 'TE', 'ST', 'DC'],
      Chapman: ['ML1', 'ML2', 'ML3', 'Ghost Fret'],
      Solar: ['A Series', 'S Series', 'E Series', 'V Series', 'AB Series'],
      Agile: ['AL', 'Interceptor', 'Septor', 'Hawker', 'Pendulum'],
      Tokai: ['Love Rock', 'Springy Sound', 'Breezysound', 'ES'],
      Burny: ['RLG', 'RSA', 'RSG', 'Firebird'],
      Orville: ['Les Paul', 'SG', 'ES-335', 'Firebird'],
      Greco: ['EG', 'SE', 'SA', 'MR', 'GO'],
      Edwards: ['E-LP', 'E-SE', 'E-SN', 'E-SA', 'E-HR'],
      Mayones: ['Regius', 'Duvell', 'Setius', 'Legend'],
      Framus: ['Panthera', 'Diablo', 'Mayfield', 'Idolmaker'],
      Vigier: ['Excalibur', 'GV', 'Expert', 'Surfreter'],
      Parker: ['Fly', 'NiteFly', 'P-Series', 'MaxxFly'],
      Fernandes: ['Ravelle', 'Monterey', 'Vertigo', 'Dragonfly', 'Retrorocket'],
      Aria: ['Pro II', 'RS', 'PE', 'TA', 'Cardinal'],
      Teisco: ['Spectrum', 'Del Rey', 'E-100', 'EP'],
      Silvertone: ['1448', '1457', '1478', 'U1'],
      Supro: ['Belmont', 'Coronado', 'Dual-Tone', 'Westbury']
    }
  },
  Acoustic: {
    label: 'Acoustic Guitar',
    aliases: ['Acoustic Guitar', 'Flat Top'],
    brands: {
      Martin: ['D-18', 'D-28', 'D-35', 'HD-28', 'OM-28', '000-18', '000-28', '00-18', 'LX1', 'SC-13E', 'Road Series', 'X Series'],
      Taylor: ['Baby Taylor', 'GS Mini', 'Academy', '100 Series', '200 Series', '300 Series', '400 Series', '500 Series', '600 Series', '700 Series', '800 Series', '900 Series', 'Grand Auditorium', 'Grand Concert', 'Grand Pacific', 'T5z'],
      Gibson: ['J-45', 'Hummingbird', 'Dove', 'SJ-200', 'J-200', 'L-00', 'LG-2', 'Songwriter'],
      Epiphone: ['Inspired by Gibson J-45', 'Hummingbird', 'Dove', 'Texan', 'Masterbilt', 'AJ'],
      Guild: ['D-55', 'D-40', 'D-20', 'F-512', 'F-55', 'M-20', 'OM', 'Westerly'],
      Yamaha: ['FG', 'FS', 'APX', 'CPX', 'LL', 'LS', 'A Series', 'TransAcoustic'],
      Takamine: ['G Series', 'Pro Series', 'EF', 'GD', 'GN', 'P Series'],
      Alvarez: ['Artist', 'Masterworks', 'Regent', 'Yairi', 'Delta DeLite'],
      Seagull: ['S6', 'Maritime', 'Artist', 'Entourage', 'Coastline'],
      Breedlove: ['Discovery', 'Pursuit', 'Organic', 'Premier', 'Concert', 'Concerto'],
      Eastman: ['E1D', 'E2D', 'E6D', 'E8D', 'E10D', 'E20D', 'OM', 'AC'],
      Cordoba: ['Fusion', 'C5', 'C7', 'C9', 'C10', 'GK Studio'],
      Kremona: ['Sofia', 'Rosa', 'Fiesta', 'Solea', 'Verea'],
      'La Patrie': ['Etude', 'Concert', 'Presentation', 'Collection'],
      Godin: ['Multiac', 'A6', 'Metropolis', 'Fairmount', 'Arena'],
      Ovation: ['Celebrity', 'Elite', 'Legend', 'Balladeer', 'Adamas'],
      Washburn: ['D Series', 'WD', 'Festival', 'Comfort', 'Heritage'],
      Fender: ['CD', 'CC', 'Malibu', 'Newporter', 'Redondo'],
      Ibanez: ['AW', 'AE', 'AEG', 'Artwood', 'Talman Acoustic', 'PC'],
      Gretsch: ['Jim Dandy', 'Rancher', 'Roots', 'G5022', 'G9500'],
      'Recording King': ['RO', 'RD', 'RP', 'Dirty 30s', 'Tonewood Reserve'],
      Blueridge: ['BR-40', 'BR-60', 'BR-70', 'BR-160', 'BR-180'],
      Collings: ['D1', 'D2H', 'OM1', 'OM2H', 'CJ', 'C10'],
      Bourgeois: ['Vintage D', 'Country Boy', 'OM', 'Soloist', 'L-DBO'],
      'Santa Cruz': ['D', 'D/PW', 'OM', 'H', 'Tony Rice'],
      Lowden: ['O', 'F', 'S', 'WL', 'Jazz'],
      Larrivee: ['D', 'OM', 'L', 'LV', 'P'],
      Maton: ['SRS', 'EBG808', 'Messiah', 'Performer', 'Mini Maton'],
      'Cole Clark': ['Fat Lady', 'Angel', 'Little Lady', 'True Hybrid'],
      'Huss & Dalton': ['TD-R', 'DS', 'OM', 'CM', 'Crossroads']
    }
  },
  Bass: {
    label: 'Bass Guitar',
    aliases: ['Bass', 'Bass Guitar'],
    brands: {
      Fender: FENDER_BASS_MODELS,
      Squier: FENDER_BASS_MODELS,
      Gibson: ['Thunderbird', 'EB Bass', 'SG Bass', 'Grabber', 'Ripper'],
      Epiphone: ['Thunderbird', 'Embassy', 'Jack Casady', 'Rivoli', 'Viola Bass'],
      Ibanez: IBANEZ_BASS_MODELS,
      Yamaha: ['TRBX', 'BB', 'RBX', 'Attitude', 'Broad Bass'],
      'Music Man': MUSIC_MAN_MODELS,
      'Sterling by Music Man': MUSIC_MAN_MODELS,
      'Ernie Ball Music Man': MUSIC_MAN_MODELS,
      Rickenbacker: ['4001', '4003', '4004', '4005'],
      Warwick: ['Corvette', 'Streamer', 'Thumb', 'Fortress', 'RockBass'],
      Spector: ['NS', 'Euro', 'Legend', 'Pulse', 'Performer'],
      Dingwall: ['Combustion', 'D-Roc', 'NG', 'ABZ', 'Z Series'],
      Lakland: ['44-64', '44-60', '55-02', 'Skyline', 'Decade'],
      Sadowsky: ['MetroLine', 'NYC', 'Modern', 'Vintage', 'Will Lee'],
      'G&L': ['L-2000', 'L-2500', 'JB', 'Kiloton', 'SB-2'],
      Schecter: ['Stiletto', 'Model-T', 'Omen Bass', 'C-4', 'C-5'],
      ESP: ESP_LTD_MODELS,
      LTD: ESP_LTD_MODELS,
      Jackson: ['Concert Bass', 'Spectra Bass', 'Kelly Bird', 'X Series Bass'],
      Charvel: ['San Dimas Bass', 'Pro-Mod Bass', 'Surfcaster Bass'],
      Hofner: ['Violin Bass', 'Club Bass', 'Verythin Bass', 'Ignition'],
      Cort: ['A Series', 'B Series', 'GB', 'Artisan', 'Action'],
      Fodera: ['Monarch', 'Emperor', 'Imperial', 'Yin Yang'],
      MTD: ['Kingston', '535', '635', 'Z Series'],
      Tobias: ['Classic', 'Killer B', 'Growler', 'Toby'],
      Alembic: ['Series I', 'Series II', 'Spoiler', 'Epic', 'Essence'],
      Peavey: ['T-40', 'Cirrus', 'Foundation', 'Millennium'],
      Reverend: ['Mercalli', 'Decision', 'Dub King', 'Thundergun'],
      Kiesel: ['JB', 'PB', 'Vanquish', 'Zeus Bass', 'Icon Bass'],
      Carvin: ['LB', 'Bunny Brunel', 'Icon Bass', 'PB'],
      'Harley Benton': ['JB', 'PB', 'Enhanced', 'Progressive', 'BZ']
    }
  },
  Classical: {
    label: 'Classical / Nylon String',
    aliases: ['Classical Guitar', 'Nylon String', 'Classical / Nylon String'],
    brands: {
      Cordoba: ['C5', 'C7', 'C9', 'C10', 'C12', 'GK Studio', 'Fusion'],
      Kremona: ['Sofia', 'Rosa', 'Fiesta', 'Solea', 'Verea'],
      Yamaha: ['C Series', 'CG Series', 'GC Series', 'NCX', 'NTX'],
      Takamine: ['GC Series', 'TC Series', 'Hirade', 'Classical'],
      Alvarez: ['Classical', 'Regent Classical', 'Yairi Classical'],
      'La Patrie': ['Etude', 'Concert', 'Presentation', 'Collection'],
      Godin: ['Multiac Nylon', 'ACS', 'Arena', 'A6 Ultra Nylon'],
      Ramirez: ['1A', '2CWE', 'Estudio', 'Conservatorio'],
      Alhambra: ['1C', '3C', '4P', '5P', '7P'],
      Esteve: ['1GR', '3GR', '6PS', '9C/B'],
      Admira: ['Alba', 'Malaga', 'A10', 'Virtuoso'],
      Hanika: ['Basis', 'Natural', 'Meisterklasse'],
      'Kenny Hill': ['New World', 'Performance', 'Player'],
      'Manuel Rodriguez': ['Caballero', 'C Series', 'E Series'],
      Ortega: ['R Series', 'Family Series', 'Feel Series']
    }
  },
  Keyboard: {
    label: 'Keyboard / Synthesizer',
    aliases: ['Keyboard', 'Synth', 'Synthesizer', 'Digital Piano', 'Stage Piano', 'MIDI Controller', 'Electric Piano', 'Organ'],
    brands: {
      Yamaha: ['DX7', 'MONTAGE', 'MODX', 'MOTIF', 'CP Series', 'YC Series', 'Reface', 'P Series', 'Clavinova', 'PSR Series'],
      Roland: ['JUNO', 'JUPITER', 'FANTOM', 'RD Series', 'FP Series', 'D-50', 'JX Series', 'SH Series', 'GAIA'],
      Korg: ['Kronos', 'Nautilus', 'Krome', 'M1', 'Triton', 'Wavestate', 'Opsix', 'Minilogue', 'Monologue', 'Prologue'],
      Nord: ['Stage', 'Electro', 'Piano', 'Wave', 'Lead'],
      Casio: ['Privia', 'Celviano', 'CT-S Series', 'WK Series', 'CZ Series'],
      Kurzweil: ['K2000', 'K2500', 'K2600', 'PC Series', 'Forte', 'SP Series'],
      Sequential: ['Prophet-5', 'Prophet-6', 'Prophet Rev2', 'Take 5', 'Trigon-6', 'OB-6'],
      Moog: ['Minimoog', 'Subsequent 37', 'Grandmother', 'Matriarch', 'Muse', 'One'],
      Arturia: ['KeyLab', 'MiniLab', 'AstroLab', 'PolyBrute', 'MatrixBrute', 'MicroFreak', 'MiniFreak'],
      Akai: ['MPC Key', 'MPK Series', 'Advance'],
      Alesis: ['QS Series', 'Quadrasynth', 'Fusion', 'Recital', 'V Series'],
      Novation: ['Launchkey', 'SL MkIII', 'Bass Station II', 'Summit', 'Peak', 'MiniNova'],
      'Native Instruments': ['Komplete Kontrol S Series', 'Komplete Kontrol A Series', 'Kontrol M Series'],
      Studiologic: ['SL Series', 'Numa Compact', 'Numa X Piano'],
      Hammond: ['SK Series', 'XK Series', 'M-Solo'],
      Rhodes: ['Mark I', 'Mark II', 'Mark V', 'MK8'],
      Wurlitzer: ['200', '200A', '206', '140B'],
      Ensoniq: ['ESQ-1', 'SQ-80', 'VFX', 'EPS', 'ASR-10', 'TS Series'],
      'E-mu': ['Emulator', 'Emax', 'Proteus', 'PK Series'],
      Kawai: ['MP Series', 'ES Series', 'CA Series', 'K Series'],
      Oberheim: ['OB-X', 'OB-Xa', 'OB-8', 'OB-X8', 'Matrix-6', 'Matrix-12']
    }
  },
  Amplifier: {
    label: 'Amplifier',
    aliases: ['Amp', 'Guitar Amplifier', 'Bass Amplifier'],
    brands: {
      Fender: ['Bassman', 'Blues Deluxe', 'Blues Junior', 'Champ', 'Deluxe Reverb', 'Hot Rod Deluxe', 'Mustang', 'Princeton Reverb', 'Pro Junior', 'Rumble 40', 'Rumble 100', 'Rumble 200', 'Rumble 500', 'Super Reverb', 'Tone Master Deluxe Reverb', 'Twin Reverb', 'Vibrolux Reverb'],
      Marshall: ['JTM45', 'Super Lead 1959', 'JMP 2203', 'JMP 2204', 'JCM800 2203', 'JCM800 2204', 'JCM900', 'JCM2000 DSL', 'JCM2000 TSL', 'DSL20', 'DSL40', 'DSL100', 'JVM', 'Origin', 'Studio Classic', 'Studio Vintage', 'Valvestate', 'MG Series'],
      Vox: ['AC4', 'AC10', 'AC15', 'AC30', 'AC50', 'AC100', 'Cambridge', 'Pathfinder 10', 'Valvetronix'],
      Orange: ['AD30', 'Crush Series', 'Dual Terror', 'OR15', 'OR120', 'Rocker 15', 'Rockerverb 50', 'Rockerverb 100', 'Super Crush 100', 'Terror Bass', 'TH30', 'TH100', 'Tiny Terror'],
      Mesa: ['Mark I', 'Mark II', 'Mark III', 'Mark IV', 'Mark V', 'Mark VII', 'Dual Rectifier', 'Triple Rectifier', 'Mini Rectifier', 'Lone Star', 'Express', 'Fillmore', 'California Tweed', 'Subway D-800'],
      Peavey: ['5150', '6505', 'Bandit 112', 'Classic 20', 'Classic 30', 'Classic 50', 'Delta Blues', 'JSX', 'Nashville 400', 'ValveKing', 'Vypyr', 'Windsor', 'XXX'],
      Ampeg: ['B-15 Portaflex', 'Gemini', 'Reverberocket', 'Rocket Bass', 'SVT', 'SVT-CL', 'V-4', 'V-4B'],
      Blackstar: ['HT-1', 'HT-5', 'HT-20', 'HT-40', 'HT-60', 'ID:Core', 'Series One', 'Silverline', 'St. James'],
      'Line 6': ['Catalyst', 'DT25', 'DT50', 'Firehawk 1500', 'Flextone', 'Spider', 'Vetta'],
      Roland: ['AC-60', 'Blues Cube', 'Cube', 'JC-22', 'JC-40', 'JC-120', 'KC Series'],
      Boss: ['Acoustic Singer', 'Katana-50', 'Katana-100', 'Katana Artist', 'Nextone', 'Waza Amp Head'],
      Yamaha: ['B100', 'DG Series', 'G100', 'GA Series', 'THR5', 'THR10', 'THR30II'],
      Supro: ['Black Magick', 'Blues King', 'Delta King', 'Keeley Custom', 'Statesman', 'Thunderbolt'],
      Magnatone: ['Panoramic Stereo', 'Starlite', 'Super Fifty-Nine', 'Twilighter', 'Varsity'],
      Friedman: ['BE-100', 'Dirty Shirley', 'JJ Junior', 'Pink Taco', 'Runt', 'Twin Sister'],
      Soldano: ['Astro-20', 'Avenger', 'Decatone', 'Hot Rod 50', 'Hot Rod 100', 'SLO-30', 'SLO-100'],
      Bogner: ['Alchemist', 'Atma', 'Ecstasy', 'Goldfinger', 'Shiva', 'Uberschall'],
      Diezel: ['D-Moll', 'Einstein', 'Hagen', 'Herbert', 'VH4', 'VHX'],
      'Hughes & Kettner': ['Black Spirit 200', 'Duotone', 'GrandMeister', 'Switchblade', 'TriAmp', 'TubeMeister'],
      Laney: ['AOR', 'Cub', 'GH Series', 'Ironheart', 'Lionheart', 'Supergroup', 'VC30', 'VH100R'],
      Crate: ['Blue Voodoo', 'FlexWave', 'GX Series', 'Palomino', 'Vintage Club', 'VTX Series'],
      'Gallien-Krueger': ['400RB', '800RB', '1001RB', 'Fusion S', 'Legacy', 'MB Fusion'],
      Aguilar: ['AG500', 'AG700', 'DB 750', 'DB 751', 'Tone Hammer 350', 'Tone Hammer 500', 'Tone Hammer 700'],
      Hartke: ['HA3500', 'HA5500', 'HD Series', 'LH500', 'LH1000', 'TX300', 'TX600'],
      'Trace Elliot': ['AH250', 'AH350', 'AH500', 'Commando', 'Elf', 'GP7', 'GP11', 'GP12'],
      Hiwatt: ['Custom 20', 'Custom 50', 'Custom 100', 'DR504', 'DR103', 'Stage', 'Studio'],
      EVH: ['5150III 50W', '5150III 100W', '5150III LBX', '5150 Iconic'],
      Engl: ['Fireball', 'Ironball', 'Invader', 'Powerball', 'Savage'],
      Egnater: ['Rebel', 'Renegade', 'Tourmaster', 'Tweaker'],
      Matchless: ['Chieftain', 'DC-30', 'HC-30', 'Lightning', 'Spitfire'],
      'Dr. Z': ['Carmen Ghia', 'MAZ 18', 'MAZ 38', 'Remedy', 'Route 66', 'Z Wreck'],
      'Bad Cat': ['Black Cat', 'Cub', 'Hot Cat', 'Lynx'],
      Victory: ['Duchess', 'Kraken', 'Sheriff', 'V30', 'V40', 'V45', 'V100'],
      PRS: ['Archon', 'Dallas', 'HDRX', 'MT 15', 'Sonzera'],
      Kemper: ['Profiler Head', 'Profiler Rack', 'Profiler Stage', 'PowerHead', 'PowerRack'],
      'Neural DSP': ['Quad Cortex'],
      Quilter: ['Aviator', 'Bass Block', 'MicroPro', 'Overdrive 200', 'Tone Block'],
      Sunn: ['200S', '2000S', 'Beta Bass', 'Beta Lead', 'Coliseum', 'Concert Bass', 'Concert Lead', 'Model T'],
      Carvin: ['Belair', 'BX500', 'Legacy', 'Nomad', 'V3', 'X100B'],
      Randall: ['Century', 'Diavlo', 'RG80', 'RG100', 'Satan', 'Warhead'],
      Traynor: ['Bass Master', 'YBA-1', 'YCV Series', 'YGL Series', 'YGM Series'],
      'Music Man': ['65 Series', 'HD-130', 'RD Series', 'Sixty-Five 112', 'Sixty-Five 210'],
      Kustom: ['Coupe', 'Defender', 'K200', 'Lead Series'],
      Silvertone: ['1482', '1484', '1485'],
      Polytone: ['Mini-Brute']
    }
  },
  Other: {
    label: 'Other',
    aliases: ['Other', 'Unknown'],
    brands: {}
  }
};
